build:
  maxIssues: -1
  excludeCorrectable: false

complexity:
  active: true
  ComplexCondition:
    active: true
    threshold: 4
  ComplexMethod:
    active: false
  LargeClass:
    active: true
    threshold: 600
  LongMethod:
    active: false
  LongParameterList:
    active: false
  NestedBlockDepth:
    active: true
    threshold: 6
  TooManyFunctions:
    active: false

coroutines:
  active: true
  SleepInsteadOfDelay:
    active: true

empty-blocks:
  active: true

exceptions:
  active: true
  SwallowedException:
    active: true
  PrintStackTrace:
    active: true
  TooGenericExceptionCaught:
    active: false

formatting:
  active: true
  android: true
  autoCorrect: true
  NoUnusedImports:
    active: true
    autoCorrect: true
  NoTrailingSpaces:
    active: true
    autoCorrect: true
  NoConsecutiveBlankLines:
    active: true
    autoCorrect: true
  ParameterListWrapping:
    active: true
    autoCorrect: true
    maxLineLength: 120
    indentSize: 2
  SpacingAroundColon:
    active: true
    autoCorrect: true
  SpacingAroundComma:
    active: true
    autoCorrect: true
  SpacingAroundCurly:
    active: true
    autoCorrect: true
  SpacingAroundDot:
    active: true
    autoCorrect: true
  SpacingAroundKeyword:
    active: true
    autoCorrect: true
  SpacingAroundOperators:
    active: true
    autoCorrect: true
  SpacingAroundParens:
    active: true
    autoCorrect: true
  SpacingAroundRangeOperator:
    active: true
    autoCorrect: true
  MaximumLineLength:
    active: false
  ImportOrdering:
    active: true
    autoCorrect: true
  Indentation:
    active: true
    autoCorrect: true
    indentSize: 2
  TrailingCommaOnCallSite:
    active: false
  TrailingCommaOnDeclarationSite:
    active: false
  Wrapping:
    active: true
    autoCorrect: true
    maxLineLength: 120
  MultiLineIfElse:
    active: true
    autoCorrect: true
  NoWildcardImports:
    active: false

naming:
  active: true
  ClassNaming:
    active: true
    classPattern: '[A-Z][a-zA-Z0-9]*'
  FunctionNaming:
    active: true
    functionPattern: '[a-z][a-zA-Z0-9]*'
    excludeClassPattern: ''
    ignoreAnnotated:
      - 'Composable'
  VariableNaming:
    active: true
    variablePattern: '[a-z][a-zA-Z0-9]*'
    privateVariablePattern: '_?[a-z][a-zA-Z0-9]*'
  TopLevelPropertyNaming:
    active: true
    constantPattern: '[A-Z][A-Za-z0-9_]*'
  PackageNaming:
    active: true
    packagePattern: '[a-z]+(\.[a-z][a-z0-9_]*)*'
  MatchingDeclarationName:
    active: false
  MemberNameEqualsClassName:
    active: false

performance:
  active: true
  ArrayPrimitive:
    active: true
  ForEachOnRange:
    active: true

potential-bugs:
  active: true
  UnsafeCallOnNullableType:
    active: true
  UnnecessaryNotNullOperator:
    active: true
  MissingPackageDeclaration:
    active: false
  EqualsWithHashCodeExist:
    active: true

style:
  active: true
  MagicNumber:
    active: false
  MaxLineLength:
    active: false
  VarCouldBeVal:
    active: true
  MayBeConst:
    active: true
  UnusedPrivateMember:
    active: true
  UnnecessaryApply:
    active: true
  WildcardImport:
    active: false
  ReturnCount:
    active: false
  ForbiddenComment:
    active: false
  UseDataClass:
    active: false
  NewLineAtEndOfFile:
    active: true
    autoCorrect: true
  OptionalAbstractKeyword:
    active: true
  UtilityClassWithPublicConstructor:
    active: false
  UnnecessaryAbstractClass:
    active: false
